import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const V10LET = localFont({
  src: "../public/V1OLET-Regular.otf",
  display: "swap",
  variable: "--font-violet",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${V10LET.variable} ${inter.className}`}>{children}</body>
    </html>
  );
}
